### PR TITLE
Add input focus with keyboard suggestions

### PR DESCRIPTION
**Pull request by vhoyer**
This should deal with magic numbers the color accessibility and I also removed the changes in size of the input that were present on your branch so the size of the search box stays consistent between master and this new branch.

### CODE REVIEW

**Review by LeWawan — APPROVED** [review]
Thanks for the changes @vhoyer !

**Comment by vhoyer** [comment]
if you are cool with the suggestions, you can merge then into your branch, I don't have permission to mess with your branch here ahah

**Comment by LeWawan** [comment]
Hey @vhoyer 

I just tested your code, the display of the indication outside the input is design of yours ?
I have the impression that it is less clear for the user than when it is inside the input.

What do you think about it?

**Comment by vhoyer** [comment]
have you really tested it? it's visually "inside" the input, because visually the input is now the wrapper :thinking:

**Pull request merged**
